name: Build and Push Docker Image
on:
  push:
    branches:
      - main
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and export to Docker
      uses: docker/build-push-action@v4
      with:
        context: .
        load: true
        tags: ${{ secrets.DOCKER_USERNAME }}/reconnaissance:test
    - name: Test
      run: |
          docker run --rm ${{ secrets.DOCKER_USERNAME }}/reconnaissance:test

    - name: Extract Version from pyproject.toml
      id: extract_version
      run: echo ::set-output name=version::$(awk -F'=' '/^version/ {print $2}' pyproject.toml | sed -e 's/^ *//g' -e 's/ *$//g' -e 's/"//g')
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/reconnaissance:${{ steps.extract_version.outputs.version }}