name: Build and Push Docker Image
on:
  push:
    branches:
      - main
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract Version from pyproject.toml
      id: extract_version
      run: echo ::set-output name=version::$(awk -F'=' '/^version/ {print $2}' pyproject.toml | sed -e 's/^ *//g' -e 's/ *$//g' -e 's/"//g')

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm64/v8
        file: Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/reconnaissance:${{ steps.extract_version.outputs.version }}
